on:
  push:
    branches: [ main, develop ]

name: Build Angular
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v1

      - name: Extract branch name
        # https://stackoverflow.com/questions/58033366/how-to-get-current-branch-within-github-actions
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch
      
      - name: build Docker image
        run: |
          case ${{ steps.extract_branch.outputs.branch }} in
            develop) CONFIGURATION=development ;;
            main) CONFIGURATION=production ;;
          esac
          make build CONFIGURATION=${CONFIGURATION}

      - name: publish Docker image
        env:
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          echo $DOCKERHUB_TOKEN | sudo docker login --username $DOCKERHUB_USERNAME --password-stdin 
          make publish
